import type { AwbAcademyLessonReplacement } from "./lessonReplacements.js";

export const trackLessonReplacements: AwbAcademyLessonReplacement[] = [
  {
    slug: "asc_ortho_surgical_wound_types_complication_taxonomy",
    title: "Surgical wound types & complication taxonomy",
    track: "ASC / Ortho Track",
    course: "Surgical wound types & complication taxonomy",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Welcome. In this lesson, we organize surgical wounds into a practical taxonomy that supports assessment, communication, and escalation. Start by separating clean incisions, traumatic surgical wounds, dehisced wounds, graft or flap donor and recipient sites, and wounds complicated by infection, ischemia, hematoma, seroma, or hardware exposure. The goal is not just labeling. The goal is understanding what threatens closure. When you assess a postop wound, ask: is this healing on the expected timeline, or is there a complication changing the risk profile? Taxonomy matters because documentation drives decisions, coding logic, and team response. A superficial separation is different from full-thickness dehiscence. Erythema without drainage is different from purulence with systemic signs. A stable dry eschar is different from tissue loss over a pressure point after immobilization. Use precise language, note anatomic site, closure type, drainage, tissue integrity, edge condition, surrounding skin, pain pattern, and any implanted material. A wound described correctly is easier to defend, treat, and monitor.`,
  },
  {
    slug: "asc_ortho_recipient_bed_preparation",
    title: "Recipient bed preparation",
    track: "ASC / Ortho Track",
    course: "Recipient bed preparation",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Recipient bed preparation determines whether advanced closure strategies have a real chance to succeed. Before applying a graft, biologic, or cellular tissue product, confirm the wound bed is ready. That means nonviable tissue has been addressed, bioburden is controlled, moisture is appropriate, perfusion concerns are recognized, and the wound has a healthy, supportable surface. Granulation alone is not enough. The bed must be clean, vascularized, and free of obvious barriers to incorporation. Document pre-application wound dimensions, tissue composition, exudate, undermining, tunneling, exposed structures, and signs that delay closure such as edema, pressure, shear, infection, or uncontrolled glucose. State what preparation was performed and why it was necessary. In procedural settings, link bed preparation to the medical goal: optimize adherence, reduce non-take risk, and support orderly healing. Avoid vague phrases like wound cleaned and ready. Instead, describe the condition before preparation, the intervention performed, and the status after preparation. Good preparation is clinical, operational, and evidentiary.`,
  },
  {
    slug: "asc_ortho_skin_grafting_fundamentals_in_asc",
    title: "Skin grafting fundamentals in ASC",
    track: "ASC / Ortho Track",
    course: "Skin grafting fundamentals in ASC",
    durationMin: 9,
    owner: "AWB Academy",
    script: `This lesson covers the practical fundamentals of skin grafting in the ambulatory surgery center. Start with case selection. The wound needs a recipient bed that can support take, and the patient needs a plan for edema control, protection, and follow-up. Understand the distinction between autograft, allograft, xenograft, and other adjunctive materials, and be precise about what is being applied. In the ASC, success depends on workflow discipline: site confirmation, bed preparation, product verification, sizing, securement, dressing selection, and postop instructions. Graft failure is often not one dramatic event. It is a chain of small preventable misses, such as residual necrosis, excessive motion, shear, pooled fluid, or poor offloading. Document the rationale for grafting, wound status immediately before application, product or graft details, area treated, fixation method, dressing plan, and follow-up interval. The more complex the closure strategy, the more important the documentation becomes. Technical execution matters, but so does proving why the intervention was appropriate.`,
  },
  {
    slug: "asc_ortho_biologic_adjuncts_ctp_workflow",
    title: "Biologic adjuncts and CTP workflow",
    track: "ASC / Ortho Track",
    course: "Biologic adjuncts and CTP workflow",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Biologic adjuncts and cellular or tissue-based products belong inside a disciplined workflow, not a product-first mindset. Begin with indication. Why is standard management no longer enough, and what specific barrier are you trying to overcome? Then confirm readiness: adequate bed preparation, moisture balance, infection control, pressure mitigation, and a follow-up plan. Next comes product workflow. Verify identity, size, storage status, expiration, handling requirements, and traceability fields before the package is opened. Record the treated area, amount applied, any wastage, and securement method. In the ASC and ortho environment, coordination matters because timing, sterility, and product handling are tightly linked. The chart should show a straight line from wound status to medical necessity to product selection to application technique to postoperative protection. That is what makes the case clinically coherent and operationally reliable. A strong workflow reduces errors, supports reimbursement logic, and improves the odds that the intervention performs as intended.`,
  },
  {
    slug: "asc_ortho_postop_monitoring_documentation",
    title: "Postop monitoring and documentation",
    track: "ASC / Ortho Track",
    course: "Postop monitoring and documentation",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Postoperative monitoring is where good procedures either stay on track or begin to unravel. Your job is to identify early signals of complication before they become failures. Monitor pain trend, drainage pattern, dressing integrity, edema, temperature changes, edge stability, graft appearance if applicable, and the condition of surrounding skin. Note whether the expected healing trajectory is present. Stable improvement is not the same as no change, and no change is not the same as deterioration. Documentation should always compare today's findings with the prior visit. Include wound dimensions when appropriate, tissue appearance, exudate character, odor if present, adherence to offloading or immobilization instructions, and any escalation steps taken. Avoid generic statements like doing well. Instead, describe objective findings and the plan tied to those findings. Good postop documentation protects the patient first. It also protects the team by showing that complications were actively watched for, recognized, and managed with clinical reasoning rather than hindsight.`,
  },
  {
    slug: "asc_ortho_ortho_specific_considerations",
    title: "Ortho-specific considerations",
    track: "ASC / Ortho Track",
    course: "Ortho-specific considerations",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Orthopedic wounds bring issues that general wound workflows may understate. Hardware, casts, braces, limited mobility, swelling, pressure points, and altered biomechanics all change healing risk. In ortho, wound status cannot be separated from structural stability and load management. Ask whether the wound is being stressed by motion, edema, friction, or device contact. Also ask whether deeper structures or implants may be involved. A small superficial concern over hardware can carry outsized risk. Your documentation should connect the wound to the orthopedic context: procedure type, site, mobility restrictions, brace or immobilizer use, offloading strategy, infection concern, and communication with the operating team. Be especially careful with drainage timing, tissue separation, exposed tendon or hardware, and pressure injuries related to splints or immobilization. The best ortho wound notes show that the clinician understands both tissue healing and mechanical realities. Healing is not only a biologic process here. It is also an engineering problem.`,
  },
  {
    slug: "asc_ortho_claims_defensibility_audit_readiness",
    title: "Claims defensibility & audit readiness",
    track: "ASC / Ortho Track",
    course: "Claims defensibility & audit readiness",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Claims defensibility starts long before a payer asks questions. It begins with a chart that tells a complete, consistent, medically necessary story. In the ASC and ortho setting, auditors look for internal coherence. Does the diagnosis match the wound description? Does the procedure note match the product used? Do the dimensions support the amount billed? Is there a clear reason advanced care was needed? Build your documentation around those questions. Identify the wound clearly, describe the clinical problem, record what conservative or standard measures were attempted when relevant, document the state of the bed before intervention, capture product traceability and wastage, and state the postoperative plan. Avoid copy-paste drift, mismatched laterality, and templated phrases that do not fit the case. An auditor should be able to reconstruct the clinical logic without guessing. Strong audit readiness is not decorative paperwork. It is structured proof that the service was appropriate, supported, and executed with documented rationale.`,
  },

  {
    slug: "dist_wound_care_ecosystem_terminology_l1",
    title: "Wound care ecosystem & terminology lesson 1",
    track: "Distributor Track",
    course: "Wound care ecosystem & terminology",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In this first lesson, we map the wound care ecosystem. Distributors operate inside a network that includes physicians, nurse practitioners, surgery centers, post-acute facilities, home health, billing teams, manufacturers, and patients. Each stakeholder uses overlapping terminology, but not always with the same precision. Your role is to reduce confusion, not amplify it. Know the difference between chronic wound, acute wound, surgical wound, debridement, graft, dressing, biologic adjunct, and cellular or tissue-based product. Also understand the difference between clinical terminology and commercial shorthand. The closer your language stays to accepted clinical meaning, the less friction you create. This foundation matters because a distributor is often the bridge between product logistics and real-world care pathways. When you understand who does what and how the vocabulary is used, your communication becomes more accurate, compliant, and useful.`,
  },
  {
    slug: "dist_wound_care_ecosystem_terminology_l2",
    title: "Wound care ecosystem & terminology lesson 2",
    track: "Distributor Track",
    course: "Wound care ecosystem & terminology",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson focuses on terminology that shapes operations. Learn the practical meaning of order intake, verification, site onboarding, chain of custody, storage controls, traceability, treated area, wastage, recipient bed, and follow-up interval. These are not just words for paperwork. They define how product moves safely and compliantly from source to site of care. Distributors need to understand the difference between what can be described operationally and what crosses into clinical judgment. For example, you can confirm required fields, but you should not independently reinterpret wound severity or tell providers what to document. Your value is process clarity, product accountability, and communication discipline. When terminology is used consistently across teams, fewer delays occur, fewer errors appear, and audits are easier to support.`,
  },
  {
    slug: "dist_wound_care_ecosystem_terminology_l3",
    title: "Wound care ecosystem & terminology lesson 3",
    track: "Distributor Track",
    course: "Wound care ecosystem & terminology",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson three, we connect terminology to field execution. The most effective distributor teams understand which words trigger action. If a site says delayed case, temperature excursion, partial shipment, expired lot, substitution request, or documentation mismatch, each phrase should lead to a defined response. Build a shared vocabulary across sales, customer service, operations, and compliance so that everyone understands the same event the same way. Precision in language reduces preventable mistakes. It also protects credibility with clinicians and facilities. Your goal is to make the process easier without overstepping. The right terminology allows you to move faster, escalate earlier, and communicate in a way that supports clinical care while staying in the proper lane.`,
  },

  {
    slug: "dist_chain_custody_traceability_storage_l1",
    title: "Chain of custody, traceability, and storage controls lesson 1",
    track: "Distributor Track",
    course: "Chain of custody, traceability, and storage controls",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Chain of custody begins the moment a product enters your control. In this lesson, focus on the basic principles: who handled the product, when custody changed, where it was stored, and whether required conditions were maintained. Traceability is only as strong as the weakest handoff. That means lot numbers, product identifiers, package integrity, storage logs, and receiving records must align. Do not treat this as back-office detail. In advanced wound care, traceability supports patient safety, inventory reliability, recall response, and audit support. A product that cannot be fully traced becomes operational risk. Your standard should be simple: every movement is documented, every exception is visible, and every discrepancy is investigated.`,
  },
  {
    slug: "dist_chain_custody_traceability_storage_l2",
    title: "Chain of custody, traceability, and storage controls lesson 2",
    track: "Distributor Track",
    course: "Chain of custody, traceability, and storage controls",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson covers storage controls in day-to-day operations. Some products are sensitive to temperature, handling, timing, or package damage. Storage controls are not optional preferences. They are part of product integrity. Teams should know acceptable ranges, quarantine rules, labeling expectations, access limitations, and documentation requirements for variances. If a shipment arrives with questionable condition, stop the workflow and escalate. Never let schedule pressure override control standards. Storage failures do more than create waste. They can compromise patient care and expose the entire distribution chain during review. A disciplined storage program reduces substitution emergencies, protects trust with sites, and creates a clean evidentiary record.`,
  },
  {
    slug: "dist_chain_custody_traceability_storage_l3",
    title: "Chain of custody, traceability, and storage controls lesson 3",
    track: "Distributor Track",
    course: "Chain of custody, traceability, and storage controls",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson three, we focus on exception handling. What happens when there is a missing lot record, a temperature question, a damaged package, or an uncertain handoff? Mature teams do not improvise these moments. They follow an incident pathway. Quarantine the item when needed, document the issue immediately, notify the right internal owner, and avoid creating downstream uncertainty for the site. The best traceability systems are not just good during normal operations. They remain usable under stress. Build workflows that make the correct action the easy action. If you can show clean chain-of-custody history and disciplined exception management, you are not just moving product. You are protecting the program.`,
  },

  {
    slug: "dist_ordering_workflows_site_onboarding_l1",
    title: "Ordering workflows & site onboarding lesson 1",
    track: "Distributor Track",
    course: "Ordering workflows & site onboarding",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Ordering workflows begin with clean intake. A strong process defines who can place orders, what information is required, how site identity is verified, and how missing fields are resolved without chaos. During onboarding, confirm facility details, authorized contacts, shipping logic, storage readiness, receiving procedures, and escalation paths. Many order problems start because the site was never truly onboarded. Distributors reduce friction when they standardize intake rather than customizing every case informally. The aim is simple: right site, right product, right documentation, right timing. A stable onboarding process prevents avoidable downstream calls, delays, and misunderstandings.`,
  },
  {
    slug: "dist_ordering_workflows_site_onboarding_l2",
    title: "Ordering workflows & site onboarding lesson 2",
    track: "Distributor Track",
    course: "Ordering workflows & site onboarding",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In this lesson, we look at operational reliability. Ordering is not just receiving a request. It is verifying the request against approved workflow. Who is requesting? Is the site active? Is the product appropriate for the site's handling capability? Are shipping and receipt windows aligned with treatment timing? These checks protect both the distributor and the facility. Good onboarding also establishes communication norms: who gets updates, how substitutions are addressed, and how urgent issues are escalated. Distributors that formalize these steps look easier to work with because they create predictability. Predictability is one of the most valuable products you can deliver.`,
  },
  {
    slug: "dist_ordering_workflows_site_onboarding_l3",
    title: "Ordering workflows & site onboarding lesson 3",
    track: "Distributor Track",
    course: "Ordering workflows & site onboarding",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Lesson three ties ordering to customer experience and compliance. The fastest workflow is not always the safest workflow. A mature onboarding model balances speed with controls. That means using checklists, approved site profiles, documented contact trees, and clear rules for urgent requests. When errors do occur, the best teams can quickly see whether the issue began at intake, verification, fulfillment, shipment, or site receipt. That visibility only exists when onboarding and ordering workflows are standardized. Your goal is not complexity. It is a repeatable system that keeps the field moving without creating hidden risk.`,
  },

  {
    slug: "dist_documentation_logistics_reduce_friction_l1",
    title: "Documentation logistics that reduce friction lesson 1",
    track: "Distributor Track",
    course: "Documentation logistics that reduce friction",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Documentation logistics can either speed access or create constant rework. In lesson one, focus on required fields, clean handoffs, and timing. Many delays happen because documents are incomplete, illegible, mismatched, or submitted too late in the process. The distributor's role is to make requirements visible early and route documents consistently. Use standardized intake, naming conventions, version control, and issue flags so teams know what is missing and why. This is not about pressuring clinicians to say more. It is about reducing avoidable process friction and helping sites submit usable records the first time.`,
  },
  {
    slug: "dist_documentation_logistics_reduce_friction_l2",
    title: "Documentation logistics that reduce friction lesson 2",
    track: "Distributor Track",
    course: "Documentation logistics that reduce friction",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson addresses common documentation bottlenecks. Duplicate requests, unclear checklists, fragmented email chains, and inconsistent file capture all slow care and frustrate sites. Build a workflow that identifies what is required, who owns collection, who validates completeness, and where exceptions go. The language matters too. Ask for specific missing elements rather than broad statements like incomplete chart. When sites understand exactly what is needed, turnaround improves. Strong documentation logistics make the distributor look organized, reduce back-and-forth, and support cleaner downstream review.`,
  },
  {
    slug: "dist_documentation_logistics_reduce_friction_l3",
    title: "Documentation logistics that reduce friction lesson 3",
    track: "Distributor Track",
    course: "Documentation logistics that reduce friction",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson three, we connect documentation to scale. A process that works for ten cases may fail at one hundred if it depends on tribal knowledge. Use documented workflows, role ownership, and quality checks. Track where friction occurs most often: intake errors, unreadable files, missing signatures, timing delays, or site confusion. Then redesign around the recurring failure points. The distributor does not control all documentation, but it can control how documentation moves. That is where major efficiency gains live. Better logistics reduce frustration, shorten cycle times, and support a more defensible operation.`,
  },

  {
    slug: "dist_returns_wastage_substitutions_compliance_l1",
    title: "Returns, wastage, substitutions, and compliance lesson 1",
    track: "Distributor Track",
    course: "Returns, wastage, substitutions, and compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Returns, wastage, and substitutions create risk when handled casually. Start with definitions. A return is not the same as unused product on site. Wastage is not the same as spoilage. A substitution is not just a customer service favor. Each event has operational and compliance implications. Teams need written rules for what can be returned, what must be quarantined, how wastage is recorded, and who can authorize substitutions. Consistency matters because inconsistent handling creates audit exposure and inventory distortion. Your job is to make these edge cases controlled, not improvised.`,
  },
  {
    slug: "dist_returns_wastage_substitutions_compliance_l2",
    title: "Returns, wastage, substitutions, and compliance lesson 2",
    track: "Distributor Track",
    course: "Returns, wastage, substitutions, and compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson focuses on documentation standards for exception events. If product is returned, document the reason, status, condition, and chain of custody. If there is wastage, record the context and required internal fields. If a substitution is requested, document who requested it, what changed, why the change occurred, and whether the site is authorized to proceed. Never let verbal convenience replace formal recordkeeping. These events are exactly where regulators, auditors, and internal reviewers tend to look. Strong documentation allows the organization to explain what happened without reconstructing the story later.`,
  },
  {
    slug: "dist_returns_wastage_substitutions_compliance_l3",
    title: "Returns, wastage, substitutions, and compliance lesson 3",
    track: "Distributor Track",
    course: "Returns, wastage, substitutions, and compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Lesson three is about judgment under pressure. Urgent cases can create temptation to cut corners around substitutions or exception handling. Do not let speed erase control. A compliant team knows when to pause, escalate, or decline a request that cannot be supported. That discipline protects patients, sites, and the distributor. Mature organizations build playbooks for common exception patterns so field teams are not guessing. The goal is simple: resolve issues quickly, but never ambiguously. When returns, wastage, and substitutions are handled with documented rigor, the whole program becomes safer and more trusted.`,
  },

  {
    slug: "dist_audit_support_incident_response_l1",
    title: "Audit support & incident response lesson 1",
    track: "Distributor Track",
    course: "Audit support & incident response",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Audit support starts before any audit exists. In lesson one, build the mindset that records should already be organized, retrievable, and internally coherent. You should be able to locate product identifiers, shipment history, custody records, storage logs, site communication, and exception handling without a scramble. Incident response follows the same principle. If something goes wrong, speed matters, but clarity matters more. Teams need a standard pathway for documenting facts, preserving records, notifying the correct owners, and controlling speculation. Good audit support is really good operational hygiene performed consistently.`,
  },
  {
    slug: "dist_audit_support_incident_response_l2",
    title: "Audit support & incident response lesson 2",
    track: "Distributor Track",
    course: "Audit support & incident response",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson focuses on what reviewers want to see. During an audit or incident review, they are looking for chronology, accountability, and consistency. Can you show what was ordered, what was shipped, what was received, what was documented, and what happened when a problem emerged? Avoid fragmented records and inconsistent narratives. Keep responses factual, time-linked, and supported by source documentation. In incident response, define who leads, who gathers facts, who communicates externally, and how corrective action is tracked. Structure beats improvisation every time.`,
  },
  {
    slug: "dist_audit_support_incident_response_l3",
    title: "Audit support & incident response lesson 3",
    track: "Distributor Track",
    course: "Audit support & incident response",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson three, we turn audit support into a capability. Review your own processes before someone else does. Test whether records are complete, whether exception paths are followed, and whether incident logs tell a clear story. Conduct mock drills for product discrepancies, storage questions, and urgent site escalations. The goal is not perfection. It is readiness. When a distributor can respond with calm, organized facts, confidence goes up across the company and with external partners. Audit support and incident response are not separate from operations. They are proof that operations are under control.`,
  },

  {
    slug: "postacute_facility_wound_workflow_roles",
    title: "Facility wound workflow & roles",
    track: "Post-Acute & Senior Care Track",
    course: "Facility wound workflow & roles",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Wound outcomes in post-acute care depend heavily on workflow clarity. In this lesson, define who does what, when, and how handoffs occur. Nursing staff identify changes, complete routine skin checks, and execute ordered care. Providers assess, diagnose, and adjust treatment plans. Therapy, dietary teams, administrators, and family often influence mobility, nutrition, and adherence. The problem in many facilities is not lack of effort. It is role confusion. When no one owns the next step, wounds worsen quietly. Create a structured pathway from admission screening to routine surveillance to escalation. Standardize how new wounds are reported, how measurements are recorded, when provider review occurs, and how follow-up is tracked. The facility should function like a system, not a series of isolated tasks. A reliable wound workflow improves healing, reduces avoidable deterioration, and creates documentation that reflects coordinated care.`,
  },
  {
    slug: "postacute_pressure_injury_prevention_risk_scoring",
    title: "Pressure injury prevention + risk scoring",
    track: "Post-Acute & Senior Care Track",
    course: "Pressure injury prevention + risk scoring",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Pressure injury prevention begins before the wound exists. Risk scoring tools such as Braden or Norton are useful only when they trigger action. A score alone does not prevent anything. In this lesson, connect risk scoring to interventions: repositioning, support surfaces, moisture control, nutrition attention, mobility planning, and heel protection. Reassess risk with any material change in condition such as illness, decline in mobility, incontinence, sedation, or poor intake. Documentation should show the score, the risk factors behind it, and the preventive measures that followed. If a pressure injury develops, reviewers will look backward. They will ask whether risk was identified and whether the facility acted. Strong prevention documentation shows not just awareness, but execution. Prevention is most defensible when the plan is individualized, monitored, and revised as the resident's condition changes.`,
  },
  {
    slug: "postacute_barrier_screening_impacts_healing",
    title: "Barrier screening that impacts healing",
    track: "Post-Acute & Senior Care Track",
    course: "Barrier screening that impacts healing",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Wounds do not heal in isolation from the rest of the patient. Barrier screening identifies the factors that make progress stall. In the post-acute setting, common barriers include poor glycemic control, vascular insufficiency, malnutrition, low albumin context, immobility, incontinence, edema, smoking, infection risk, and medication-related issues. This lesson teaches teams to screen systematically rather than react only when the wound worsens. The value is practical: once barriers are visible, the care plan becomes more realistic. Document the barrier, the evidence suggesting it, and the action taken or recommended. A wound with persistent drainage plus lower-extremity edema may need more than a dressing change. A pressure injury in a resident with poor intake and immobility will not improve through local care alone. Good screening makes the treatment plan more credible and more effective.`,
  },
  {
    slug: "postacute_offloading_support_surfaces_compliance_doc",
    title: "Offloading, support surfaces, and compliance documentation",
    track: "Post-Acute & Senior Care Track",
    course: "Offloading, support surfaces, and compliance documentation",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Pressure redistribution and offloading are fundamental, but they only matter if implemented consistently. This lesson covers the practical side of support surfaces, heel protection, seating strategies, turning schedules, and device-related pressure prevention. In the post-acute environment, the challenge is usually not knowing what offloading means. It is proving that the ordered strategy was actually carried out. Documentation should show the risk, the selected intervention, the resident-specific limitations, and observed adherence or barriers. If the resident refuses, cannot tolerate, or repeatedly disrupts the plan, that belongs in the record along with the response. Compliance documentation is not punitive. It explains why the wound is or is not improving. Offloading failures often look like clinical failure on the surface. In reality, they are execution failures. Clear documentation helps distinguish the difference.`,
  },
  {
    slug: "postacute_wound_assessment_measurement_standardization",
    title: "Wound assessment & measurement standardization",
    track: "Post-Acute & Senior Care Track",
    course: "Wound assessment & measurement standardization",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Standardization turns wound documentation from opinion into usable data. Measure consistently using the same approach each time: length, width, depth when appropriate, undermining, tunneling, tissue type, exudate, odor if present, edge condition, periwound, pain, and signs of deterioration or improvement. Inconsistent technique makes progress impossible to interpret. One nurse's small wound can become another nurse's larger wound simply because the method changed. This lesson establishes a common language so facility staff and providers can compare findings over time with confidence. The key is repeatability. Document not only the wound, but how the wound is changing relative to prior visits. Standardized assessments improve care decisions, support escalation when needed, and make the chart more credible during review.`,
  },
  {
    slug: "postacute_debridement_documentation_basics",
    title: "Debridement documentation basics",
    track: "Post-Acute & Senior Care Track",
    course: "Debridement documentation basics",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Debridement documentation must show necessity, execution, and result. Even when the actual procedure is performed by an authorized clinician, facility staff contribute key observations before and after. The record should describe what nonviable tissue or devitalized material was present, why removal was needed, and what changed after debridement. Capture wound measurements, tissue composition, drainage, pain or tolerance observations if applicable, and the post-procedure appearance. Avoid vague language such as cleaned up wound. Debridement changes the wound bed and often the treatment trajectory. The note should make that clear. In post-acute settings, strong documentation also supports communication between facility staff and providers. Everyone should understand what was done, what the wound looks like now, and what the next step is.`,
  },
  {
    slug: "postacute_escalation_advanced_modalities_skin_substitutes",
    title: "Escalation to advanced modalities + skin substitutes",
    track: "Post-Acute & Senior Care Track",
    course: "Escalation to advanced modalities + skin substitutes",
    durationMin: 9,
    owner: "AWB Academy",
    script: `Escalation to advanced care should happen for clinical reasons, not because the team is frustrated. This lesson teaches when a wound has reached the point where standard management is no longer enough. Before escalation, confirm that fundamentals were actually executed: pressure relief, moisture balance, infection control, vascular considerations, nutrition support, and follow-up consistency. Then document why progress remains inadequate. The chart should tell a logical story from standard care to persistent barrier to advanced consideration. In post-acute settings, skin substitutes or other advanced modalities require especially clear coordination among facility staff, providers, and supply workflows. Escalation is strongest when the record shows both diligence and failure of simpler measures. That is what makes the next step medically coherent.`,
  },

  {
    slug: "provider_advanced_wound_assessment_staging_l1",
    title: "Advanced wound assessment & staging lesson 1",
    track: "Provider Track",
    course: "Advanced wound assessment & staging",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Advanced wound assessment starts with etiology before treatment selection. In lesson one, focus on reading the wound in context. Is this pressure, venous, arterial, diabetic, surgical, traumatic, mixed, or moisture-associated damage? A wound described without etiologic thinking is only half assessed. Look at location, shape, margins, tissue pattern, exudate, pain profile, surrounding skin, and relevant systemic factors. Staging and classification matter, but they are not interchangeable across wound types. Use the right framework for the right wound. A provider-level assessment should translate bedside findings into a reasoned diagnostic impression and treatment direction.`,
  },
  {
    slug: "provider_advanced_wound_assessment_staging_l2",
    title: "Advanced wound assessment & staging lesson 2",
    track: "Provider Track",
    course: "Advanced wound assessment & staging",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson two, we address depth, tissue involvement, and classification discipline. Know when a pressure injury can be staged, when it is unstageable, when deep tissue injury language applies, and when a non-pressure wound should be described rather than staged. Avoid forcing every wound into the wrong framework. Document exposed structures, undermining, tunneling, tissue percentages, bioburden clues, and periwound findings that change management. The chart should make the wound understandable to another clinician without needing to infer what you saw. Precision here improves treatment selection and later audit review.`,
  },
  {
    slug: "provider_advanced_wound_assessment_staging_l3",
    title: "Advanced wound assessment & staging lesson 3",
    track: "Provider Track",
    course: "Advanced wound assessment & staging",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson turns advanced assessment into actionable clinical reasoning. Once the wound is correctly characterized, ask what is preventing healing now. Is it ischemia, edema, pressure, shear, infection, moisture imbalance, glycemic instability, poor adherence, or an inaccurate diagnosis? Advanced assessment is not a longer description. It is a more useful one. Your note should connect the wound findings to the plan: debridement, imaging, culture strategy when appropriate, vascular referral, compression, offloading, advanced modality consideration, or follow-up interval. A high-level assessment should change what happens next.`,
  },

  {
    slug: "provider_audit_readiness_compliance_l1",
    title: "Audit readiness & compliance lesson 1",
    track: "Provider Track",
    course: "Audit readiness & compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Audit readiness for providers begins with internal consistency. Every wound note should align diagnosis, assessment, procedure details, and plan. If you document debridement, the wound characteristics should justify it. If you use advanced products, the history should show why simpler care was insufficient. Auditors do not need perfect charts. They need coherent ones. Avoid cloned language, contradictory measurements, and generic plans that ignore actual findings. Good compliance is not defensive writing. It is accurate, decision-linked documentation that reflects what happened and why.`,
  },
  {
    slug: "provider_audit_readiness_compliance_l2",
    title: "Audit readiness & compliance lesson 2",
    track: "Provider Track",
    course: "Audit readiness & compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson focuses on procedural and product-related risk areas. Capture wound size before intervention, describe tissue or pathology prompting treatment, record the method used, and state the post-procedure condition. For products, include name, size, area treated, amount used, wastage when applicable, and traceability details required by your workflow. The more advanced the intervention, the less room there is for vague charting. Compliance is strongest when the note reads like a clinically literate narrative rather than a billing template with blanks filled in.`,
  },
  {
    slug: "provider_audit_readiness_compliance_l3",
    title: "Audit readiness & compliance lesson 3",
    track: "Provider Track",
    course: "Audit readiness & compliance",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In lesson three, we build a defensible chart under real-world constraints. Most compliance failures are not dramatic fraud issues. They are slippage: missing details, copied findings, unsupported escalation, or disconnected follow-up plans. Build habits that reduce slippage. Reconcile measurements, update the problem list accurately, tailor the assessment to today's findings, and document why the next step is medically reasonable. A strong audit-ready note should allow an outside reviewer to reconstruct the case without filling in gaps from assumption.`,
  },

  {
    slug: "provider_infection_biofilm_inflammation_l1",
    title: "Infection, biofilm, inflammation lesson 1",
    track: "Provider Track",
    course: "Infection, biofilm, inflammation",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Infection, biofilm, and inflammation overlap, but they are not interchangeable. In lesson one, separate colonization from invasive infection and distinguish both from a wound stalled by chronic inflammatory burden. Look for local signs, changes in exudate, friable tissue, odor, pain shifts, delayed granulation, and undermining patterns. Biofilm is not always visible, but the wound behavior can suggest its presence. The provider's task is to interpret the pattern, not just react to a single sign. A wound that stays inflamed and static despite apparently appropriate care requires deeper thinking.`,
  },
  {
    slug: "provider_infection_biofilm_inflammation_l2",
    title: "Infection, biofilm, inflammation lesson 2",
    track: "Provider Track",
    course: "Infection, biofilm, inflammation",
    durationMin: 8,
    owner: "AWB Academy",
    script: `This lesson turns recognition into management logic. When infection is suspected, decide what evidence supports that concern and what action is proportional: debridement, imaging, culture strategy, systemic treatment, local control, or urgent escalation. When biofilm is likely, remember that one-time intervention is rarely enough. The plan usually requires repeated disruption plus supportive wound bed management. Chronic inflammation also demands barrier correction, not just topical change. Document the rationale clearly. State what signs you saw, what you think they mean, and how the treatment plan addresses the specific problem rather than using a generic wound script.`,
  },
  {
    slug: "provider_infection_biofilm_inflammation_l3",
    title: "Infection, biofilm, inflammation lesson 3",
    track: "Provider Track",
    course: "Infection, biofilm, inflammation",
    durationMin: 8,
    owner: "AWB Academy",
    script: `In this lesson, we focus on the interaction between infection, biofilm, and chronic inflammation as the core biologic barriers to wound closure. Distinguish colonization from infection: all chronic wounds contain bacteria, but infection involves tissue invasion, host response, and damage. Biofilm is a protected bacterial community that can resist antimicrobials and immune clearance, which is why wounds often plateau after early improvement. Clinical management should follow a repeatable cycle: debridement to disrupt biofilm, cleansing to remove disrupted burden, targeted topical antimicrobial support, and serial reassessment because biofilm can reform quickly. Chronic inflammatory burden also degrades growth factors and newly formed tissue, so treatment must reduce bioburden and restore a regenerative environment. Reserve systemic antibiotics for clear spread or systemic involvement; most chronic wounds require disciplined local control. The practical standard is simple: recognize the pattern, intervene proportionally, and document why each step was medically necessary.`,
  },
  {
    slug: "debridement-mastery-lesson-1",
    title: "Debridement Mastery - Lesson 1",
    track: "Provider Track",
    course: "Debridement Mastery",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Debridement is the deliberate removal of devitalized tissue, debris, and biofilm to create a wound environment capable of progression. Without debridement, necrotic burden can harbor bacteria, block epithelial migration, and limit granulation quality. In chronic wound pathways, debridement often acts as the reset step that converts a stagnant wound bed into one that can respond to therapy. Providers should know the major approaches - sharp/surgical, mechanical, autolytic, enzymatic, and biologic - and choose based on wound context, urgency, and tissue condition. Common indications include necrotic tissue, slough, biofilm burden, nonhealing wound beds, and preparation for advanced modalities. Contraindications include scenarios such as severe ischemia or stable dry eschar in selected ischemic heel contexts. The key principle is selective removal of nonviable burden while protecting viable structures and documenting rationale clearly.`,
  },
  {
    slug: "debridement-mastery-lesson-2",
    title: "Debridement Mastery - Lesson 2",
    track: "Provider Track",
    course: "Debridement Mastery",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Technique discipline drives both outcome quality and documentation quality in debridement. Start by assessing the wound bed and distinguishing viable tissue from nonviable tissue such as yellow slough, black eschar, or dense fibrotic material. Select instrumentation based on wound characteristics and procedural control needs; common tools include scalpel, curette, tissue scissors, and forceps. A practical workflow is: assess wound bed, provide local analgesia or anesthesia when needed, remove devitalized tissue selectively, control bleeding, irrigate thoroughly, and apply a dressing aligned to exudate and tissue status. The goal is to remove what impedes healing while preserving healthy structures and minimizing procedural trauma. Strong technique also requires serial reassessment between visits, because tissue state and debridement needs change over time.`,
  },
  {
    slug: "debridement-mastery-lesson-3",
    title: "Debridement Mastery - Lesson 3",
    track: "Provider Track",
    course: "Debridement Mastery",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Debridement claims are only as defensible as the note. Before the procedure, document wound size and tissue composition; after the procedure, document updated measurements, depth achieved, tissue removed, hemostasis, and post-procedure status. Use clear L x W x D format and describe tissue using supported terms such as granulation, slough, necrotic tissue, and epithelial tissue where applicable. Coding support depends on three linked facts: deepest tissue level actually removed, total treated surface area, and clear medical necessity for performing debridement at that visit. Common denials occur when depth is implied rather than documented, area is vague, or the rationale is disconnected from wound findings. The strongest notes are precise, internally consistent, and explicit about pre/post change.`,
  },
  {
    slug: "moisture-balance-dressings-advanced-modalities-lesson-1",
    title: "Moisture Balance, Dressings, and Advanced Modalities - Lesson 1",
    track: "Provider Track",
    course: "Moisture balance, dressings, and advanced modalities",
    durationMin: 8,
    owner: "AWB Academy",
    script: `Moisture balance is a core wound-healing control, not a cosmetic detail. A balanced moist environment supports epithelial migration, can reduce pain, and improves tissue regeneration conditions. Too dry leads to desiccation and stalled progress; too wet leads to maceration and peri-wound injury. Dressing strategy should reflect the wound's location, depth, drainage burden, infection risk, and surrounding skin condition. Common categories include foams, hydrocolloids, alginates, hydrogels, and antimicrobial options used when clinically indicated. High-exudate wounds require absorptive management, appropriate change cadence, and peri-wound protection. If standard local management fails despite appropriate fundamentals, advanced modalities such as negative pressure therapy or biologic/CTP pathways may be considered with clear patient selection and documentation logic.`,
  },
];
